name: Build CV

on:
  push:
    branches-ignore: [deploy]
  workflow_call:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      - name: Render the CV
        run: uv run rendercv render src/Pierre_CV.yaml

      - name: Upload output as an artifact
        uses: actions/upload-artifact@v6
        with:
          name: rendercv_output
          path: src/rendercv_output
